#ifndef COMMON_DATA_STRUCTURES_H
#define COMMON_DATA_STRUCTURES_H

enum RecordType{
    CHUNK_TYPE_ID_MALLOC = 1,
    CHUNK_TYPE_ID_FREE = 2,
    CHUNK_TYPE_ID_CALLOC = 3,
    CHUNK_TYPE_ID_REALLOC = 4,
    CHUNK_TYPE_ID_MEMALIGN = 5
};

#endif // COMMON_DATA_STRUCTURES_H

